|    Test Name   |                                              What it was testing                                              |                                              How its output is wrong                                              | What the error in the code was                                             | How you changed the program (or test input) to fix it                      |
|:--------------:|:-------------------------------------------------------------------------------------------------------------:|:-----------------------------------------------------------------------------------------------------------------:|----------------------------------------------------------------------------|----------------------------------------------------------------------------|
| test_bad_login | Testing to see if the "login failed" message appeared as the #login_msg element after a failed login attempt. | Very first test made so it didn't have access to the id of the header that would assert "login failed" on screen. | `self.assert_element("")` [It wasn't able to assert the element was there] | Added an id in the webpage under login.html checking `<h4 id="login_msg">{{message}}</h4>` | 
| test_bad_password2 | Checking that the complexity message "PUT IT HERE" appeared under #login_msg when the given password was more than 6 characters | Kept writing "Password length must be greator than 6." in #login_msg even though the password had more than 6 characters in it! | Under `backend.py` when deciding what the error message should be, it does the logic with two `if` statements under line `29` and `32`, therefore the line `32` message would always be the message since it's set after. | Changed line `32` conditional to an `elif` so it sends the desired "less than 6 characters" message when it's actually less than 6 characters. |
| login_loginFailed() 1.9.1           | redirecting to /login and show message 'email/password combination incorrect.                           | Did not show message 'email/password combination incorrect' | return None in backend.py function: def login_user(email, password):                  | Change return None to return "Email/password combination incorrect." |
| login_loginCheck() 1.1              | If the user hasn't logged in, show the login page + current page has a message that says 'please login' | Did not show message 'Please log in'                        | html element did not have an id html message did not have 'Please log in'             | Gave html element id: "login-prompt" Changed html message            |
| login_emailFormattingErrors() 1.9.1 | For any formatting errors, render the login page and show the message 'email format is incorrect.'      | Did not show message 'Email format is incorrect'            | html element did not have an id html message did not have 'Email format is incorrect' | Gave html element id: "#login_msg" Changed html message              |
| testPageHeader                      | Checking if the header on the homepage displayed the user's name correctly                              | Checked for the wrong case sensitivity in the header        | html element would check for if the header displayed "Test_frontend" instead of "test_frontend | Changed the test case to check for the correct case sensitivity |
| test404OnBuy                        | Tests for a 404 error on the unimplemented page "/buy"                                                  | The code writted just does not check for if there is a 404 error correctly | The "status" variable was supposed to be initialized with the status code of the current page, and the compared to "404", but status never became "404" for it to match | Instead of checking the status code the test now just checks for an element unique to the 404 page |
| test404OnSell                       | Same as above                                                                                           | Same as above                                               | Same as above                                                                         | Same as above                                                        |
| test404OnUpdate                     | Same as above                                                                                           | Same as above                                               | Same as above                                                                         | Same as above                                                        |
| testBuyNewTicket                    | The ticket purchasing form                                                                              | Selenium would open the form and then get stuck             | There was a mismatch between the element targeter in selenium and the id's in the html files | Both the targeter and the html were changed so that selenium interfaced with the website correctly |
| testUpdateExistingTicket            | The ticket editing form                                                                                 | Same as above                                               | Same as above                                                                         | Same as above                                                        |
| testNewTicketSubmission             | The ticket creating form                                                                                | Same as above                                               | Same as above                                                                         | Same as above                                                        |
| testNot404OnLogin                   | If there was no 404 error when visiting the login page                                                  | Selenium would falsely report that there was 404 error      | self.assert_no_404_errors() does not function correctly                               | The test case now checks for a unique element that only exists on the 404 page, and passes when that element isn't there |
| testNot404OnRegister                | If there was no 404 error when visiting the register page                                               | Same as above                                               | Same as above                                                                         | Same as above                                                        |
|test_alpha_name_pos|If a valid ticket can be created successfully|Wasn't able to successfully create a ticket due to invalid fields in the tickets|1. Had to redo indents since python didn't like indentation <br>2. #btn-buy-test was invalid <br>3. #submit-ticket-name was invalid <br>4. #submit-ticket-quantity was invalid <br>5. #submit-ticket-price was invalid <br>6. #submit-datetime was invalid <br>7. #submit-ticket-button was invalid <br>8. #sell-ticket-quantity value was an int 10 <br>9. #sell-ticket-price value was an int 20 <br>10. #sell-datetime was in incorrect format `date.today().strftime("%Y/%m/%d")`<br>11. Ticket creation didn't allow spaces " " or under-scores "_" since they didn't count as alphanumeric|1. Fixed indentation by redoing tabs<br>2. Had to change #btn-buy-test to #btn-add-ticket<br>3. Had to change #submit-ticket-name to #sell-ticket-name<br>4. Had to change #submit-ticket-quantity to #sell-ticket-quantity<br>5. Had to change #submit-ticket-price to #sell-ticket-price<br>6. Had to change #submit-datetime to #sell-datetime<br>7. Had to change #submit-ticket-button to #sell-ticket-button<br>8. Made #sell-ticket-quantity value a string "10"<br>9. Made #sell-ticket-price value a string "20"<br>10. Made #sell-datetime value `date.today().strftime("%d/%m/%Y")` for successfully getting the current date<br>11. Made sure not to test naming tickets with spaces or under-scores|
|test_alpha_name_neg|If the application recognizes when a ticket's name isn't alphanumeric, and if it doesn't allow ticket creation|`assert_element_not_present` wasn't a possible method|`assert_element_not_present` wasn't defined|had to change this check `assert_element_absent`|
|test_name_long|Checking if a name of a ticket exceeds 60 characters. Shouldn't allow ticket creation|Ticket was created between 5 and 10 characters, even though selenium was supposed to type a name of more than 60 characters|Before filling out the form, I tried to add `sleep(1)`, which sometimes wouldn't work|Had to add in a `time.sleep(1)` when inputting the information for the new ticket, since the long string being tested needs time to be typed!|
|test_handles_duplicates|Should create two of the exact tickets and check if the application doesn't allow the creation of duplicate tickets|Tried to call `test_all_pos(self)` twice to essentially make two tickets exactly the same name|This caused the error of these functions not being able to be called in this namespace|Solved this by essentially calling code to create tickets twice in a row, rather than calling the function to do this|